# Generated by Django 2.2.4 on 2019-09-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pcolor',
        ),
        migrations.AddField(
            model_name='product',
            name='pcolor',
            field=models.ManyToManyField(to='product.Color'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='psize',
        ),
        migrations.AddField(
            model_name='product',
            name='psize',
            field=models.ManyToManyField(to='product.Size'),
        ),
    ]
